config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :blog_posts
  # get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
  # get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post
  # get "/blog_posts/:id/edit", to: "blog_posts#edit", as: :edit_blog_post
  # patch "/blog_posts/:id", to: "blog_posts#update"
  # delete "/blog_posts/:id", to: "blog_posts#destroy"
  # post "/blog_posts", to: "blog_posts#create", as: :blog_posts

  # Defines the root path route ("/")
  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show] 
    before_action :set_blog_post, except: [:index, :new, :create] # kebalikan only:

    
    def index
        @blog_posts = BlogPost.all
    end

    def show       
    rescue ActiveRecord::RecordNotFound
        redirect_to root_path
    end

    def new       
        @blog_post = BlogPost.new       
    end

    def create
        @blog_post = BlogPost.new(blog_post_params)
        if @blog_post.save
            redirect_to @blog_post
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit       
    end

    def update      
        if @blog_post.update(blog_post_params)
            redirect_to @blog_post
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy       
        @blog_post.destroy
        redirect_to root_path
    end

    private
    
    def blog_post_params
      params.require(:blog_post).permit(:title, :body, :image)
    end

    def set_blog_post
        @blog_post = BlogPost.find(params[:id])
    end

    def authenticate_user! 
        redirect_to new_user_session_path, alert: "you must login!" unless user_signed_in?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/_form.html.erb
<div >
  <%= form_with model: blog_post do |form| %>
    <% if form.object.errors.any? %>
      <div >
        <% form.object.errors.full_messages.each do |message| %>
          <div>
            <%= message %>
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="space-y-3">
      <div class="flex flex-col space-y-2">
        <%= form.label :title %>
        <%= form.text_field :title %>
      </div>
      <div class="flex flex-col space-y-2">
        <%= form.label :body%>
        <%= form.text_area :body %>
      </div>
      <div>
        <%= form.file_field :image %>
      </div>
      <div>
        <%= form.button  class: "bg-blue-300 p-1"%>
      </div>
    </div>
  <% end %>
</div>

app/views/blog_posts/edit.html.erb
<div class="w-[600px] mx-auto">
  <h1 >Edit Post</h1>
  <%= render partial: "form", locals: {blog_post: @blog_post}%>
  <%= button_to "Delete", @blog_post, class: "bg-red-300 mt-3 px-2", method: :delete, data: {turbo_confirm: "are you sure?"} %>
</div>

app/views/blog_posts/index.html.erb
<div class="w-[400px] mx-auto mt-8">
  <% @blog_posts.each do |blog_post|%>
    <h4 class="text-xl font-bold my-3"><%= link_to blog_post.title, blog_post %></h4>
    <p><%= blog_post.body%></p>
    <div>
      <% if blog_post.image.present? %>
        <%= image_tag blog_post.image %>
      </div>
    <%end%>
  <%end%>
</div>

app/views/blog_posts/new.html.erb
<div class="w-[600px] mx-auto">
  <h1 class="">Add Post</h1>
  <%= render partial: "form", locals: {blog_post: @blog_post}%>
</div>

app/views/blog_posts/show.html.erb
<div class="w-[400px] mx-auto mt-8">
  <h2 class="text-xl font-bold my-3"><%=  @blog_post.title %></h2>
  <p><%= @blog_post.body %></p>
  <div>
    <% if @blog_post.image.present? %>
      <%= image_tag @blog_post.image %>
    <% end %>
  </div>
  <div class="flex flex-col space-y-3 mt-3 ">
    <%= link_to "Edit", edit_blog_post_path(@blog_post), class: "bg-blue-300 text-center py-2 w-1/3" if user_signed_in? %>
    <a href="/" class="bg-red-300 text-center py-2 w-1/3">back</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="flex  bg-blue-300 justify-evenly py-2">
      <div>
        <a href="/">Home</a>
      </div>
      <div class="flex space-x-5">
        <% if user_signed_in?%>
          <%= link_to "Create Post", new_blog_post_path%>
          <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "hover:text-red-700 " %>
        <% else %>
          <%= link_to "Login", new_user_session_path %>
          <%#= link_to "Register", new_user_registration_path %>
        <% end %>
      </div>
    </div>
    <div class="w-[600px] mx-auto mt-6">
      <p class="notice "><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>